# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Manually Compiling with Make or Cmake for test

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:

      repo-nuttx:
        description: What's the name of the repository nuttx (e.g. userGH/nuttx)?
        required: true
        type: string

      branch-nuttx:
        description: What's the name of the nuttx branch (e.g. fix-nuttx)?
        required: true
        type: string

      repo-apps:
        description: What's the name of the repository nuttx-apps (e.g. userGH/nuttx-apps)?
        required: true
        type: string

      branch-apps:
        description: What's the name nuttx-apps branch (e.g. fix-apps)?
        required: true
        type: string

      board-config:
        description: Input the board:config to be built (e.g. sim:nsh)?
        required: true
        type: string

      build-system:
        description: Choose a build system
        type: choice
        options:
          - cmake
          - make
          - all
        default: all

concurrency:
  group: build-man-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Fetch-Source:
    runs-on: ubuntu-latest
    steps:
      - name: View input parameters
        shell: bash
        run: |
          echo "Nuttx repository: ${{ inputs.repo-nuttx }}"
          echo "    Nuttx branch: ${{ inputs.branch-nuttx }}"
          echo " Apps repository: ${{ inputs.repo-apps }}"
          echo "     Apps branch: ${{ inputs.branch-apps }}"
          echo "          Config: ${{ inputs.board-config }}"
          echo "    Build system: ${{ inputs.build-system }}"

      - name: Determine Target Branches
        id: gittargets
        shell: bash
        run: |
          OS_REF=""
          APPS_REF=""
          REF="refs/heads/master"
          echo "Working with ref: $REF"

      - name: Checkout nuttx repo
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repo-nuttx }}
          ref: ${{ inputs.branch-nuttx }}
          path: sources/nuttx
          fetch-depth: 1

      - name: Checkout apps repo
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repo-apps }}
          ref: ${{ inputs.branch-apps }}
          path: sources/apps
          fetch-depth: 1

      - name: Tar sources
        run: tar zcf sources.tar.gz sources

      - name: Archive Source Bundle
        uses: actions/upload-artifact@v7.0.0
        with:
          name: source-bundle
          path: sources.tar.gz

  Linux-Make:
    if: ${{ inputs.build-system  == 'make' ||  inputs.build-system == 'all' }}
    needs: Fetch-Source
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Show Disk Space
        run: df -h

      - name: Download Source Artifact
        uses: actions/download-artifact@v8
        with:
          name: source-bundle
          path: .

      - name: Extract sources
        run: tar zxf sources.tar.gz

      - name: Docker Login
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2  # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Pull
        run: docker pull ghcr.io/apache/nuttx/apache-nuttx-ci-linux:latest

      - name: Run builds
        uses: ./sources/nuttx/.github/actions/ci-container
        env:
          BLOBDIR: /tools/blobs
        with:
          run: |
            echo "::add-matcher::sources/nuttx/.github/gcc.json"
            export ARTIFACTDIR=`pwd`/buildartifacts
            git config --global --add safe.directory /github/workspace/sources/nuttx
            git config --global --add safe.directory /github/workspace/sources/apps
            cd sources/nuttx
            ./tools/configure.sh -l ${{ github.event.inputs.board-config }}
            make V=1 -j
            artifactconfigdir=$ARTIFACTDIR/$(echo ${{ github.event.inputs.board-config }} | sed "s/:/\//")/
            echo "artifactconfigdir: $artifactconfigdir"
            mkdir -p $artifactconfigdir
            xargs -I "{}" cp "{}" $artifactconfigdir < nuttx.manifest

      - name: Post-build Disk Space
        if: always()
        run: df -h

      - uses: actions/upload-artifact@v7.0.0
        if: ${{ always() }}
        with:
          name: ${{ github.job }}-builds
          path: buildartifacts/
        continue-on-error: true

  Linux-CMake:
    if: ${{ inputs.build-system  == 'cmake' ||  inputs.build-system == 'all' }}
    needs: Fetch-Source
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Show Disk Space
        run: df -h

      - name: Download Source Artifact
        uses: actions/download-artifact@v8
        with:
          name: source-bundle
          path: .

      - name: Extract sources
        run: tar zxf sources.tar.gz

      - name: Docker Login
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2  # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Pull
        run: docker pull ghcr.io/apache/nuttx/apache-nuttx-ci-linux:latest

      - name: Run builds
        uses: ./sources/nuttx/.github/actions/ci-container
        env:
          BLOBDIR: /tools/blobs
        with:
          run: |
            echo "::add-matcher::sources/nuttx/.github/gcc.json"
            export ARTIFACTDIR=`pwd`/buildartifacts
            sourceworkspace=/github/workspace/sources
            git config --global --add safe.directory /github/workspace/sources/nuttx
            git config --global --add safe.directory /github/workspace/sources/apps
            cd sources/nuttx
            cmake -B build -DBOARD_CONFIG=${{ github.event.inputs.board-config }} -GNinja
            cmake --build build
            artifactconfigdir=$ARTIFACTDIR/$(echo ${{ github.event.inputs.board-config }} | sed "s/:/\//")/
            echo "artifactconfigdir: $artifactconfigdir"
            mkdir -p $artifactconfigdir
            cd build
            xargs -I "{}" cp "{}" $artifactconfigdir < $sourceworkspace/nuttx/build/nuttx.manifest

      - name: Post-build Disk Space
        if: always()
        run: df -h

      - uses: actions/upload-artifact@v7.0.0
        if: ${{ always() }}
        with:
          name: ${{ github.job }}-builds
          path: buildartifacts/
        continue-on-error: true
